### ISSUE TITLE
this is quite awesome

### ISSUE THREAD

**Issue by azuruce** [tamasfe/lerna-watcher#1]
this is great, by far the best watcher program I have seen. 

I wonder if it can support run everything upon start up (like chokidar's --initial)

**Comment by azuruce** [comment]
looks like just pass -runAll will work as I wanted. thanks

**Comment by tamasfe** [comment]
Thanks for the kind words.

Unfortunately I don't have a use-case for this tool anymore, contributions are welcome, but I don't think I'll be able to help and you should use it with this in mind.
